-- TABLE BUILDING
DROP TABLE IF EXISTS BUILDING CASCADE;
CREATE TABLE BUILDING (
    ID     LONG AUTO_INCREMENT,
    NAME   VARCHAR,
    CONSTRAINT BUILDING_PK PRIMARY KEY (ID),
    CONSTRAINT BUILDING_ID_UINDEX UNIQUE (ID)
);

-- TABLE ROOM
DROP TABLE IF EXISTS ROOM CASCADE;
CREATE TABLE ROOM (
    ID          LONG AUTO_INCREMENT,
    NAME        VARCHAR,
    ID_BUILDING LONG,
    FOREIGN KEY (ID_BUILDING) REFERENCES BUILDING(ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    CONSTRAINT ROOM_PK PRIMARY KEY (ID),
    CONSTRAINT ROOM_ID_UINDEX UNIQUE (ID)
);

-- TABLE INSTRUCTOR
DROP TABLE IF EXISTS INSTRUCTOR CASCADE;
CREATE TABLE INSTRUCTOR (
    ID          LONG AUTO_INCREMENT,
    FIRSTNAME   VARCHAR,
    LASTNAME    VARCHAR,
    CONSTRAINT INSTRUCTOR_PK PRIMARY KEY (ID),
    CONSTRAINT INSTRUCTOR_ID_UINDEX UNIQUE (ID)
);

-- TABLE GRADE
DROP TABLE IF EXISTS GRADE CASCADE;
CREATE TABLE GRADE (
    ID          LONG AUTO_INCREMENT,
    NAME        VARCHAR,
    CONSTRAINT GRADE_PK PRIMARY KEY (ID),
    CONSTRAINT GRADE_ID_UINDEX UNIQUE (ID)
);

-- TABLE STUDENT
DROP TABLE IF EXISTS STUDENT CASCADE;
CREATE TABLE STUDENT (
    ID          LONG AUTO_INCREMENT,
    FIRSTNAME   VARCHAR,
    LASTNAME    VARCHAR,
    ID_GRADE    LONG,
    FOREIGN KEY (ID_GRADE) REFERENCES GRADE(ID)
     ON DELETE CASCADE
     ON UPDATE NO ACTION,
    CONSTRAINT STUDENT_PK PRIMARY KEY (ID),
    CONSTRAINT STUDENT_ID_UINDEX UNIQUE (ID)
);

-- TABLE MODULE
DROP TABLE IF EXISTS MODULE CASCADE;
CREATE TABLE MODULE (
    ID          LONG AUTO_INCREMENT,
    NAME        VARCHAR,
    ID_GRADE    LONG,
    FOREIGN KEY (ID_GRADE) REFERENCES GRADE(ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    CONSTRAINT MODULE_PK PRIMARY KEY (ID),
    CONSTRAINT MODULE_ID_UINDEX UNIQUE (ID)
);

-- TABLE SESSION
DROP TABLE IF EXISTS SESSION CASCADE;
CREATE TABLE SESSION (
    ID              LONG AUTO_INCREMENT,
    BEGIN           TIMESTAMP,
    FINISH          TIMESTAMP,
    ID_MODULE       LONG,
    ID_INSTRUCTOR   LONG,
    ID_ROOM         LONG,
    FOREIGN KEY (ID_MODULE) REFERENCES MODULE(ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    FOREIGN KEY (ID_INSTRUCTOR) REFERENCES INSTRUCTOR(ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    FOREIGN KEY (ID_ROOM) REFERENCES ROOM(ID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    CONSTRAINT SESSION_PK PRIMARY KEY (ID),
    CONSTRAINT SESSION_ID_UINDEX UNIQUE (ID)
);
